name: Jekyll site CI

on:
  push:
    branches: [ "pdf" ]
  pull_request:
    branches: [ "pdf" ]

jobs:
  build:

    runs-on: String-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker sit \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/ -c "chmod -R 777 /srv/jekyll && brain build --future"
xxx
